name: Require One Of Labels
description: Fail if PR lacks any required labels
inputs:
  label_names_csv:
    description: Comma-separated label names that are allowed/required
    required: true
runs:
  using: composite
  steps:
    - name: Check PR labels
      uses: actions/github-script@v7
      with:
        script: |
          const required = core.getInput('label_names_csv').split(',').map(s => s.trim()).filter(Boolean);
          if (required.length === 0) {
            core.setFailed('No required labels provided.');
            return;
          }
          if (context.eventName !== 'pull_request') {
            core.info('Not a pull_request event, skipping label requirement.');
            return;
          }
          const labels = context.payload.pull_request.labels?.map(l => l.name) ?? [];
          core.info(`Required: ${required.join(', ')}`);
          core.info(`Present: ${labels.join(', ')}`);
          const ok = labels.some(l => required.includes(l));
          if (!ok) core.setFailed(`PR must include at least one of: ${required.join(', ')}`);
      env:
        GITHUB_TOKEN: ${{ github.token }}
