name: Require Label
description: Fail PRs that lack at least one required label

inputs:
  label_names_csv:
    description: Comma-separated list of labels that satisfy the requirement
    required: true

runs:
  using: "composite"
  steps:
    - name: Enforce required labels
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const csv = process.env.LABEL_NAMES_CSV || '';
          const required = csv
            .split(',')
            .map(s => s.trim())
            .filter(Boolean);

          if (required.length === 0) {
            core.setFailed('No required labels provided.');
            return;
          }

          if (context.eventName !== 'pull_request' && context.eventName !== 'pull_request_target') {
            core.info(`Event "${context.eventName}" is not a pull_request event, skipping label requirement.`);
            return;
          }

          const prNumber = context.payload.pull_request.number;

          const labels = await github.paginate(
            github.rest.issues.listLabelsOnIssue,
            {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            }
          );

          const present = labels.map(l => l.name);

          core.info(`Required: ${required.join(', ')}`);
          core.info(`Present: ${present.join(', ') || '(none)'}`);

          const ok = required.some(label => present.includes(label));

          if (!ok) {
            core.setFailed(`PR must include at least one of: ${required.join(', ')}`);
          } else {
            core.info('Required label present ✅');
          }
      env:
        LABEL_NAMES_CSV: ${{ inputs.label_names_csv }}
