name: Kleff Labels Provisioning
description: Parse unified kleff-labels.json into labeler.yml + labels.json and expose semantic types

inputs:
  config_repo:
    description: Repo containing org-wide defaults (fallback)
    default: kleffio/.github
  config_ref:
    description: Branch/commit for config_repo
    default: main
  unified_path:
    description: Path to the unified labels JSON file
    default: configs/labels.json

outputs:
  labeler_path:
    description: Path to generated labeler config
    value: ${{ steps.mk.outputs.labeler_path }}
  labels_path:
    description: Path to generated labels sync config
    value: ${{ steps.mk.outputs.labels_path }}
  types_csv:
    description: Comma-separated semantic types
    value: ${{ steps.mk.outputs.types_csv }}
  label_names_csv:
    description: Comma-separated label names
    value: ${{ steps.mk.outputs.label_names_csv }}

runs:
  using: composite
  steps:
    - name: Checkout caller
      uses: actions/checkout@v4

    - name: Checkout org configs (fallback)
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.config_repo }}
        ref: ${{ inputs.config_ref }}
        path: .org-config

    - name: Set up Python (for PyYAML)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PyYAML
      shell: bash
      run: pip install --no-deps --disable-pip-version-check pyyaml

    - name: Ensure unified file present
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p .generated
        if [ -f "${{ inputs.unified_path }}" ]; then
          echo "Using repo-local ${{ inputs.unified_path }}"
          cp "${{ inputs.unified_path }}" .generated/kleff-labels.json
        elif [ -f ".org-config/${{ inputs.unified_path }}" ]; then
          echo "Using org fallback .org-config/${{ inputs.unified_path }}"
          cp ".org-config/${{ inputs.unified_path }}" .generated/kleff-labels.json
        else
          echo "::error::Unified labels file not found at ${{ inputs.unified_path }} (repo) or in org fallback."
          exit 1
        fi

    - name: Build generated files
      id: mk
      shell: bash
      run: |
        set -euo pipefail
        python - <<'PY'
        import os, sys, json, yaml

        src = ".generated/kleff-labels.json"
        with open(src, "r", encoding="utf-8") as f:
            data = json.load(f)

        labels = data.get("labels", [])
        if not isinstance(labels, list) or not labels:
            print("::error::No 'labels' array found in unified file.", file=sys.stderr)
            sys.exit(1)

        labeler = {}
        for entry in labels:
            name = entry["name"]
            rules = (entry.get("rules") or {})
            changed = (rules.get("changed_files") or [])
            branchp = (rules.get("branch_patterns") or [])
            blocks = []
            if changed:
                blocks.append({"changed-files": [{"any-glob-to-any-file": changed}]})
            if branchp:
                blocks.append({"head-branch": branchp})
            if blocks:
                labeler[name] = blocks

        sync = [{
            "name": e["name"],
            "color": str(e.get("color", "")).strip().lstrip("#"),
            "description": e.get("description", "")
        } for e in labels]

        types = []
        for e in labels:
            for t in (e.get("semantic_types") or []):
                if t not in types:
                    types.append(t)
        names = [e["name"] for e in labels]

        os.makedirs(".generated", exist_ok=True)
        with open(".generated/labeler.yml", "w", encoding="utf-8") as f:
            yaml.safe_dump(labeler, f, sort_keys=False, allow_unicode=True)
        with open(".generated/labels.json", "w", encoding="utf-8") as f:
            json.dump(sync, f, ensure_ascii=False, indent=2)

        # outputs
        with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as fh:
            print("labeler_path=.generated/labeler.yml", file=fh)
            print("labels_path=.generated/labels.json", file=fh)
            print("types_csv=" + ",".join(types), file=fh)
            print("label_names_csv=" + ",".join(names), file=fh)
        PY
