name: Kleff Labels Prepare
description: Parse unified labels.yml into labeler.yml + labels.yml and expose semantic types

inputs:
  config_repo:
    description: Repo containing org-wide defaults (fallback)
    default: kleffio/.github
  config_ref:
    description: Branch/commit for config_repo
    default: main
  unified_path:
    description: Path to the unified labels file
    default: configs/labels.yml

outputs:
  labeler_path:
    description: Path to generated labeler config
    value: ${{ steps.mk.outputs.labeler_path }}
  labels_path:
    description: Path to generated labels sync config
    value: ${{ steps.mk.outputs.labels_path }}
  types_csv:
    description: Comma-separated semantic types
    value: ${{ steps.mk.outputs.types_csv }}
  label_names_csv:
    description: Comma-separated label names
    value: ${{ steps.mk.outputs.label_names_csv }}

runs:
  using: composite
  steps:
    - name: Checkout caller
      uses: actions/checkout@v4

    - name: Checkout org configs (fallback)
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.config_repo }}
        ref: ${{ inputs.config_ref }}
        path: .org-config

    - name: Ensure unified file present
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p .generated
        if [ -f "${{ inputs.unified_path }}" ]; then
          echo "Using repo-local ${{ inputs.unified_path }}"
          cp "${{ inputs.unified_path }}" .generated/kleff-labels.yml
        elif [ -f ".org-config/${{ inputs.unified_path }}" ]; then
          echo "Using org fallback .org-config/${{ inputs.unified_path }}"
          cp ".org-config/${{ inputs.unified_path }}" .generated/kleff-labels.yml
        else
          echo "::error::Unified labels file not found at ${{ inputs.unified_path }} (repo) or in org fallback."
          exit 1
        fi

    - name: Build generated files
      id: mk
      shell: bash
      run: |
        set -euo pipefail
        python3 - <<'PY'
        import os, sys, yaml

        SRC = ".generated/kleff-labels.yml"
        with open(SRC, "r", encoding="utf-8") as f:
          data = yaml.safe_load(f)

        labels = data.get("labels", [])
        if not isinstance(labels, list) or not labels:
          print("::error::No 'labels' array found in unified file.", file=sys.stderr)
          sys.exit(1)

        labeler = {}
        for e in labels:
          name = e["name"]
          rules = e.get("rules", {})
          changed = rules.get("changed_files", [])
          branchp = rules.get("branch_patterns", [])

          blocks = []
          if changed:
            blocks.append({"changed-files": [{"any-glob-to-any-file": changed}]})
          if branchp:
            blocks.append({"head-branch": branchp})
          if blocks:
            labeler[name] = blocks

        sync = []
        for e in labels:
          color = str(e.get("color", "") or "")
          # normalize to lowercase hex without '#'
          color = color.lstrip("#").lower()
          sync.append({
            "name": e["name"],
            "color": color,
            "description": e.get("description", "") or ""
          })

        types = []
        for e in labels:
          for t in (e.get("semantic_types") or []):
            if t not in types: types.append(t)
        names = [e["name"] for e in labels]

        os.makedirs(".generated", exist_ok=True)

        with open(".generated/labeler.yml","w", encoding="utf-8") as f:
          yaml.safe_dump(labeler, f, sort_keys=False, allow_unicode=True)

        with open(".generated/labels.yml","w", encoding="utf-8") as f:
          yaml.safe_dump(sync, f, sort_keys=False, allow_unicode=True, default_style='"')

        out = os.environ["GITHUB_OUTPUT"]
        with open(out, "a", encoding="utf-8") as gh:
          gh.write(f"labeler_path=.generated/labeler.yml\n")
          gh.write(f"labels_path=.generated/labels.yml\n")
          gh.write(f"types_csv={','.join(types)}\n")
          gh.write(f"label_names_csv={','.join(names)}\n")
        PY
