name: Bug Report
description: Report a bug
labels: [bugfix]
body:
  - type: textarea
    id: what-happened
    attributes: { label: What happened?, description: Steps to reproduce }
    validations: { required: true }
