name: Feature Request
description: Propose an enhancement
labels: [feature]
body:
  - type: textarea
    id: proposal
    attributes: { label: Proposal, description: What and why? }
    validations: { required: true }
