name: require-label
on:
  workflow_call:
    inputs:
      required:
        type: string
        required: false
        default: "feature,bugfix,chore,docs,refactor,security,tests"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-labels-action@v2
        with:
          mode: minimum
          count: 1
          labels: ${{ inputs.required }}
